### ISSUE TITLE
Permettre a une image d'apparaitre en fondu

### ISSUE THREAD

**Issue by Garou1111** [Clembs/nuit-de-linfo-2024#5]
Ajouter une fonctionnalité qui permet de faire apparaitre une image en fondu.

**Comment by clembs** [comment]
càd ?

**Comment by Garou1111** [comment]
Pour expliquer, quand on descend sur le site, le plan est de faire apparaitre la nageuse prêt des systèmes océaniques concernées. Le but est de faire qu'au lieu d'une image statique sur la page, l'image apparait en fondu ("fade in") à l'endroit où elle serait normalement situé.
